### ISSUE TITLE
installDepedencies typo

### ISSUE THREAD

**Issue by valentinschabschneider** [column-st/fastapi-openapi-specs-action#2]
The action input is `installDepedencies` but in the entrypoint `installDepe**n**dencies` is read.
https://github.com/column-st/fastapi-openapi-specs-action/blob/e0b4060bfa18a2d2795a4e596ee88ab551da1b20/entrypoint.py#L14C67-L14C67

**Comment by synchronizing** [comment]
Merged #3, fixing this. Thanks for reporting & MR.
